---
title: "admixture_results"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(popkin)
library(gdata)
```

# load covariate files from curegn and tgp
```{r}
data_curegn <- read_tsv( '/datacommons/ochoalab/curegn/patient-data.txt.gz' ) %>% filter(ns == TRUE) %>% 
  select(id, sex, race, diagnosis = ns) %>% 
  mutate(sex = ifelse(sex == 1, "male", "female"), 
         race = ifelse(race == "Multiracial", "Other", ifelse(race == "NatAmr", "Other", 
                                                              ifelse(race == "Pacific", "Other", 
                                                                     ifelse(race == "Unknown", "Other", race)))))
data_tgp <- read_tsv( '/datacommons/ochoalab/ssns_gwas/imputed/patient-data.txt.gz', col_types = 'cccccdciiii' ) %>% 
  filter(dataset == "tgp") %>% 
  select(id, sex, race, ancestry, diagnosis) %>% mutate(diagnosis = "FALSE") %>% 
  mutate(race = ifelse(race == "Hispanic", "Other",  race)) %>% select(-ancestry)
data <- gdata::combine(data_curegn, data_tgp) %>% mutate(diagnosis = ifelse(diagnosis == "TRUE", 1, 0)) %>% 
  mutate(source = str_remove(source, "data_"))
table(data$race)

```

# total individuals: 4356
# load Q matrix
```{r fig.width=15, fig.height=4}
admix_outQ <- read_table("/datacommons/ochoalab/curegn/merge_tgp/admixture/curegn_tgp_merge_maf10.5.Q", col_names = FALSE) 
names(admix_outQ) <- 1:5

# add race and id to Q matrix
admix_race = cbind(admix_outQ, data$id, data$race, data$source) %>% 
  mutate( `data$race` = as.factor(`data$race`))

# arrange by datasource/race
admix_arrange = admix_race %>% arrange(`data$race`, `data$source`) %>% 
  mutate(`data$race` = as.character(`data$race`), `data$source` = as.character(`data$source`), race_source = paste0(`data$race`, ":", `data$source`))
```

# initial admixture plot
```{r fig.width=24, fig.height=5}
Q_mat = as.matrix(admix_arrange[,1:5])
Q <- Q_mat[ , admix_order_cols( Q_mat ) ]
plot_admix( admix_arrange[,1:5], labs = admix_arrange$`race_source`)

```


# filter major ancestry by 80%, SAS by 50%
# arrange individuals by each ancestry subgroup separately
```{r fig.width=8, fig.height=3}
AFR = admix_arrange %>% dplyr::filter(`1` > 0.8 & `data$race` == "Black") %>% 
  arrange(-`1`)
AFR_admix = admix_arrange %>% dplyr::filter(`1` <= 0.8 & `data$race` == "Black")  %>% 
  arrange(-`1`)
EUR = admix_arrange %>% dplyr::filter(`4` > 0.8 & `data$race` == "White")  %>% 
  arrange(-`4`)
EUR_admix = admix_arrange %>% dplyr::filter(`4` <= 0.8 & `data$race` == "White") %>% 
  arrange(-`4`)
EAS = admix_arrange %>% dplyr::filter(`3` > 0.8 & `data$race` == "Asian") %>% 
  arrange(-`3`)
SAS = admix_arrange %>% dplyr::filter(`5` > 0.8 & `data$race` == "Asian") %>% 
  arrange(-`5`)
EAS_admix = admix_arrange %>% dplyr::filter(`3` <= 0.8 & `data$race` == "Asian") %>% 
  filter(!`data$id` %in% SAS$`data$id`)
SAS_admix = admix_arrange %>% dplyr::filter(`5` <= 0.8 & `data$race` == "Asian") %>% 
  filter(!`data$id` %in% EAS$`data$id`)
# in SAS shouldn't be in EAS_admix
# in EAS shouldn't be in SAS_admix
Asian_admix = combine(EAS_admix, SAS_admix) %>% distinct(data.id, .keep_all = TRUE) %>% select(-source) %>%
  rename(`1` = X1, `2` = X2, `3` = X3, `4` = X4, `5` = X5,
         `data$id` = data.id, `data$race` = data.race, `data$source` = data.source) %>% 
  arrange(-`5`)
Other =  admix_arrange %>% filter(`data$race` == "Other") %>% 
  arrange(-`2`)
```

# cleaned up admixture plot after 80% filter for AFR and EUR and 50% filter for SAS
```{r fig.width=8, fig.height=3}
test = combine(AFR, AFR_admix, EUR, EUR_admix, SAS, EAS, Asian_admix, Other) %>%
  rename(African = X1, European = X4, 'South Asian' = X5, 'East Asian' = X3, 'Native American' = X2,
         `data$id` = data.id, `data$race` = data.race, `data$source` = data.source) %>% arrange(source) %>% 
  mutate(source = as.character(source)) %>% 
  select(African, European, 'South Asian','East Asian', 'Native American', everything())
plot_admix( test[,1:5], labs = test$source, labs_cex = 0.9, labs_las =1, leg_width = 0.1,
            labs_line = 2, xlab_line = 0.7, leg_cex = 0.8, labs_even = TRUE)
```

# split groups by ancestry and data source (curegn/tgp)
```{r fig.width=8, fig.height=3}
test = combine(AFR, AFR_admix, EUR, EUR_admix, SAS, EAS, Asian_admix, Other) %>%
  rename(African = X1, European = X4, 'South Asian' = X5, 'East Asian' = X3, 'Native American' = X2,
         `data$id` = data.id, `data$race` = data.race, `data$source` = data.source) %>% arrange(source) %>% 
  mutate(source = as.character(source), new_label = as.character(paste0(source,":",`data$source`))) %>% 
  arrange(match(new_label, c("AFR:curegn", "AFR:tgp", "AFR_admix:curegn", "AFR_admix:tgp",
                             "EUR:curegn", "EUR:tgp", "EUR_admix:curegn", 
                             "SAS:curegn", "SAS:tgp", "Asian_admix:curegn", "Asian_admix:tgp",
                             "EAS:curegn", "EAS:tgp", 
                             "Other:curegn", "Other:tgp"))) %>% 
  select(African, European, 'South Asian','East Asian', 'Native American', everything())
table(test$new_label, test$source)
plot_admix( test[,1:5], labs = test$new_label, labs_cex = 0.6, labs_las =1, leg_width = 0.1,
            labs_line = 2, xlab_line = 0.7, leg_cex = 0.8, labs_even = TRUE)
table(test$new_label)
```

