
```{r}
#library(devtools)
library(ggplot2)
#install_github("camillemmoore/Power_Genetics", subdir="genpwr")
library(genpwr)
library(ggrepel)
library(tidyverse)
```

```{r}
# for NS vs control
n_cases <- 994
n_controls <- 3558
# total sample size N
N = n_cases + n_controls

pw <- genpwr.calc(calc = "power", model = "logistic", ge.interaction = NULL,
   N=N, Case.Rate=n_cases/N, k=NULL,
   MAF=seq(0.05, 0.3, by = 0.05), OR=seq(1.1, 3.0, by = 0.1) , Alpha=5e-8,
   True.Model="Additive", 
   Test.Model="Additive")


head(pw)
tail(pw)


pw$MAF <- factor(pw$MAF, levels = rev(levels(as.factor(pw$MAF))))

ggplot(pw, aes(x = OR, y = `Power_at_Alpha_5e-08`, color = as.factor(MAF))) +
  geom_line() +
  xlab("OR") +
  ylab("Power") +
  theme_minimal() +
   theme(
    plot.title = element_text(hjust = 0.5),  # Center the plot title
    #legend.position = "none",  # Remove the legend
    axis.line = element_line(color = "black"),  # Set axis lines to black
    panel.grid.major.y = element_line(color = "lightgray"),
    panel.grid.major = element_blank(),  # Remove major gridlines
    panel.grid.minor = element_blank()  # Remove minor gridlines
  ) +
  geom_hline(yintercept = 0.8, linetype = "dashed", color = "darkgray") +
  labs(color = "MAF")
```

```{r}
# attempt to write MAF near each colored line
ggplot(pw, aes(x = OR, y = `Power_at_Alpha_5e-08`, color = as.factor(MAF))) +
  geom_line() +
  xlab("OR") +
  ylab("Power") +
  theme_minimal() +
   theme(
    plot.title = element_text(hjust = 0.5),  # Center the plot title
    #legend.position = "none",  # Remove the legend
    axis.line = element_line(color = "black"),  # Set axis lines to black
    panel.grid.major.y = element_line(color = "lightgray"),
    panel.grid.major = element_blank(),  # Remove major gridlines
    panel.grid.minor = element_blank()  # Remove minor gridlines
  ) +
  geom_hline(yintercept = 0.8, linetype = "dashed", color = "blue") +
  geom_text(
    data = pw %>% group_by(MAF) %>% slice(n()), 
    aes(label = MAF), 
    vjust = -0.5,  # Adjust this value to place the label slightly above the line
    show.legend = FALSE  # Remove the legend
  ) 
```

