---
title: "AF_postprocessing"
output: html_document
date: "2023-08-02"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ochoalabtools)
```

```{r}
# run from this location
setwd( '/datacommons/ochoalab/ssns_gwas/nephrotic.syndrome.gwas_proprocessing_202205/allele_freq2/' )

# Read plink output files
arr_afr <- read_tsv("array_controls_afr.afreq", col_types = 'icccdi')
arr_eur <- read_tsv("array_controls_eur.afreq", col_types = 'icccdi')
arr_sas <- read_tsv("array_controls_sas.afreq", col_types = 'icccdi')
tgp_afr <- read_tsv("tgp_controls_afr.afreq", col_types = 'icccdi')
tgp_eur <- read_tsv("tgp_controls_eur.afreq", col_types = 'icccdi')
tgp_sas <- read_tsv("tgp_controls_sas.afreq", col_types = 'icccdi')

# gather into a single table, so the plot looks the same as for original af-test (faceted the same way), except here we don't separate reverse complement SNPs.  This version we don't store (no p-values or any other fancy annotations needed later).
m <- nrow( tgp_afr )
data <- tibble(
    WGS   = c( tgp_afr$ALT_FREQS, tgp_eur$ALT_FREQS, tgp_sas$ALT_FREQS ),
    Array = c( arr_afr$ALT_FREQS, arr_eur$ALT_FREQS, arr_sas$ALT_FREQS ),
    ancestry = c( rep.int( 'African', m ), rep.int( 'European', m ), rep.int( 'South Asian', m ) )
)

# visualize results by ancestry
# these are full-page figs, scale (w/h) appropriately
dims <- fig_scale( 1/2 )
fig_start(
    'af-test',
    width = dims[1],
    height = dims[2]
)
ggplot( data, aes( x = Array, y = WGS ) ) +
    labs( x = 'Array allele frequency', y = 'WGS allele frequency' ) +
    theme_classic() +
    xlim( 0, 1 ) +
    ylim( 0, 1 ) +
    geom_point( size = 0.25 ) + 
    facet_grid( ancestry ~ . )
fig_end()
```
