---
title: "covariate analysis + MAC threshold analysis"
output: html_document
---

* create covariate file for NS + TGP data
* run simple trait ~ sex + race model
* plot gcta results after incorporating covariates
* compare different MAC threshold results

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(qqman)
```

```{r}
pheno_file = read.table("ssns_tgp_pheno_imp.txt", sep = " ", stringsAsFactors=FALSE, quote = "", header = FALSE) %>% 
  select(famid = V2, pheno = V3)
pheno_file %>% filter(famid == "19891275")

pheno_race_sex <- read.table("merge_pheno_race_sex.txt", sep = " ", stringsAsFactors=FALSE, quote = "", header = TRUE) %>% 
  mutate(famid = gsub("\\_.*", "", famid))
tgp = pheno_race_sex %>% filter(sex != 0) %>% rename(Sex = sex) %>% mutate(Sex = as.factor(ifelse(Sex == 2, "female", "male")),
                                                                           Group = as.factor(Group), Phenotype = as.factor(Phenotype))

NS_data = read_csv("pheno_excelmerge.csv") %>% 
  rename(famid = AcquisitionNumber) %>% 
  mutate(Sex = as.factor(Sex), Phenotype = as.factor(ifelse(DIAGNOSIS == "Control", 0, 1)), Group = as.factor(RACE)) %>% 
  select(famid, Sex, Group, Phenotype)

length(intersect(tgp$famid, NS_data$famid))
pheno_combine = rbind(tgp, NS_data)

ssns_tgp_pheno = merge(pheno_file, pheno_combine, by = "famid", all.x = TRUE) %>% 
  mutate(Group = ifelse(Group == "Mixed" | Group == "Unknown" | Group == "Other"| is.na(Group), "Other", as.character(Group)),
         Sex = ifelse(Sex == "unknown" | Sex == "Unknown" | is.na(Sex), "unknown", as.character(Sex)),
         Phenotype = ifelse(is.na(Phenotype), 0, as.character(Phenotype))) %>% 
  mutate(Group = as.factor(Group), Sex = as.factor(Sex), Phenotype = as.factor(Phenotype)) 
unique(ssns_tgp_pheno$Phenotype)
ssns_tgp_pheno %>% filter(is.na(Phenotype))

covar_file = ssns_tgp_pheno %>% mutate(iid = famid) %>% select(famid, iid, Sex, Group)


covar_order = covar_file[match(pheno_file$famid, covar_file$famid),]
table(covar_order$Sex)

write.table(covar_order,"covar_ns_tgp.txt", sep=" ",row.names = FALSE, quote = FALSE)
tail(ssns_tgp_pheno)

#trait ~ sex + pop

g = glm(Phenotype ~ Sex + Group, data = ssns_tgp_pheno, family=binomial)
summary(g)
```



```{r}
NS_data = read_csv("pheno_excelmerge.csv") %>% rename(famid = AcquisitionNumber)

merge(pheno_race_sex, NS_data, by = "famid", all.x = TRUE)
```

```{r}
length(setdiff(pheno_race_sex$famid, NS_data$AcquisitionNumber))
```


```{r}
library(qqman)
gcta_out <- read.table("gcta_alpha_10.mlma", sep = "\t", stringsAsFactors=FALSE, quote = "", header = TRUE)
gcta_rm6 = gcta_out %>% filter(Chr != 6)
hist(gcta_out$p, main= "Histogram of GCTA p-values", xlab = "p")
hist(gcta_rm6$p, main= "Histogram of GCTA p-values (rm chr6)", xlab = "p")

results = gcta_out %>% select(SNP, CHR = Chr, BP = bp, P = p) %>% drop_na(P)
qq(results$P)

results_rm6 = gcta_rm6 %>% select(SNP, CHR = Chr, BP = bp, P = p) %>% drop_na(P)
qq(results_rm6$P)

manhattan(results,  annotateTop = FALSE, main = "GCTA: NS + TGP (alpha 10)")
```

```{r}
gcta_out <- read.table("gcta_alpha_10_covar.mlma", sep = "\t", stringsAsFactors=FALSE, quote = "", header = TRUE)
gcta_rm6 = gcta_out %>% filter(Chr != 6)
hist(gcta_out$p, main= "Histogram of GCTA p-values", xlab = "p")
hist(gcta_rm6$p, main= "Histogram of GCTA p-values (rm chr6)", xlab = "p")

results = gcta_out %>% select(SNP, CHR = Chr, BP = bp, P = p) %>% drop_na(P)
qq(results$P)

results_rm6 = gcta_rm6 %>% select(SNP, CHR = Chr, BP = bp, P = p) %>% drop_na(P)
qq(results_rm6$P)

manhattan(results,  annotateTop = FALSE, main = "GCTA: NS + TGP (alpha 10) covar SEX + GROUP")
```

MAC analysis
```{r}
gcta_unfilter = read.table("ssns_tpg_impute.mlma", sep = "\t", stringsAsFactors=FALSE, quote = "", header = TRUE)
gcta_maf = read.table("ssns_tpg_impute_maf_new.mlma", sep = "\t", stringsAsFactors=FALSE, quote = "", header = TRUE)

```

10 minor allele counts is this MAF if n=4500 individuals:
10/(4500*2) = 0.00111111111111111
```{r}
#10 MAC:
mac = 10
n = 4485
maf = mac/(n*2) 
mac_10 = gcta_unfilter %>% filter(Freq < maf)

maf = 0.01
mac = maf*(n*2)


mac = 8
maf = mac/(n*2) 
mac_8 = gcta_unfilter %>% filter(Freq < maf)


mac = 6
maf = mac/(n*2) 
mac_6 = gcta_unfilter %>% filter(Freq < maf)
```

```{r}
mac_10 = read.table("mac_10.txt", sep = " ", stringsAsFactors=FALSE, quote = "", header = TRUE)
mac_8 = read.table("mac_8.txt", sep = " ", stringsAsFactors=FALSE, quote = "", header = TRUE)

mac_10_rm6 = mac_10 %>% filter(Chr != 6)
hist(mac_10$p, main= "MAC 10", xlab = "p")
hist(mac_10_rm6$p, main= "MAC 10 (rm chr6)", xlab = "p")

results = mac_10 %>% select(SNP, CHR = Chr, BP = bp, P = p) %>% drop_na(P)
qq(results$P)

results_rm6 = mac_10_rm6 %>% select(SNP, CHR = Chr, BP = bp, P = p) %>% drop_na(P)
qq(results_rm6$P)

manhattan(results,  annotateTop = FALSE, main = "MAC 10")
```

```{r}
mac_8_rm6 = mac_8 %>% filter(Chr != 6)
hist(mac_8$p, main= "MAC 8", xlab = "p")
hist(mac_8_rm6$p, main= "MAC 8 (rm chr6)", xlab = "p")

results = mac_8 %>% select(SNP, CHR = Chr, BP = bp, P = p) %>% drop_na(P)
qq(results$P)

results_rm6 = mac_8_rm6 %>% select(SNP, CHR = Chr, BP = bp, P = p) %>% drop_na(P)
qq(results_rm6$P)

manhattan(results,  annotateTop = FALSE, main = "MAC 8")
```

```{r}
mac_6_rm6 = mac_6 %>% filter(Chr != 6)
hist(mac_6$p, main= "MAC 6", xlab = "p")
hist(mac_6_rm6$p, main= "MAC 6 (rm chr6)", xlab = "p")

results = mac_6 %>% select(SNP, CHR = Chr, BP = bp, P = p) %>% drop_na(P)
qq(results$P)

results_rm6 = mac_6_rm6 %>% select(SNP, CHR = Chr, BP = bp, P = p) %>% drop_na(P)
qq(results_rm6$P)

manhattan(results,  annotateTop = FALSE, main = "MAC 6")
```
