---
title: "association_analysis"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
library(BEDMatrix)
.libPaths("/datacommons/ochoalab/tiffany_data")
library(ligera)
library(genio)
```

# create new phenotype file (for gcta and ligera)
```{r}
name <- '/datacommons/ochoalab/ssns_gwas/imputation/merge/ssns_tgp'
X <- BEDMatrix( name )
X[1379:1400, 1379:1400]

fam_ssnstgp <- read_fam( name ) %>% rename(ssns_id = id)
fam_ssnstgp %>% filter(ssns_id == "NA19625")
```

```{r}
pheno <- read.table("/datacommons/ochoalab/ssns_gwas/phenotype_filtered.txt", sep = "\t", stringsAsFactors=FALSE, quote = "", header = TRUE)

# t2d original encoding: 0 - control; 1 - case
# plink: 1=unaffected (control), 2=affected (case)

pheno_ = pheno %>% mutate(Phenotype = ifelse(Phenotype == "Control", 1, 2), ssns_id = paste0(ID,"_",ID)) %>% 
  dplyr::select(ssns_id, Phenotype)

```

```{r}
#merge_ids = fam_ssnstgp %>%  separate(id, c("id", "ssns_id")) %>% dplyr::select(id, ssns_id)
merge_pheno = merge(fam_ssnstgp, pheno_, by = "ssns_id", all.x = TRUE) %>% mutate(Phenotype = ifelse(is.na(Phenotype) == TRUE, 1, Phenotype), id = ssns_id) %>% dplyr::select(famid = fam, id, Phenotype) #%>% unite(id, c(fam, id))

merge_pheno[1379,]

write.table(merge_pheno,"/datacommons/ochoalab/tiffany_data/DATA_NS_MERGE/merge_pheno.txt", sep=" ",row.names = FALSE, quote = FALSE)
```


Pheno file for GMMAT
```{r}
phenodf <- read.table("/datacommons/ochoalab/ssns_gwas/phenotype_filtered.txt", sep = "\t", stringsAsFactors=FALSE, quote = "", header = TRUE) 

pheno_ = phenodf %>% mutate(Phenotype = ifelse(Phenotype == "Control", 0, 1)) %>% select(ssns_id = ID, Group, Phenotype)
```

```{r}
ssnstgp = fam_ssnstgp  %>%  mutate(famid = ssns_id) %>% separate(ssns_id, c("id", "ssns_id")) %>% select(famid, ssns_id, sex) 
ssnstgp_1 = merge(ssnstgp, pheno_, by = "ssns_id", all.x = TRUE)
ssnstgp_1[1379,]
sum(is.na(ssnstgp_1$Group))
```



```{r}
name <- '/datacommons/ochoalab/tgp/tgp-nygc-autosomes'
# phenotype ==1, controls
fam_tgp <- read_fam( name ) %>% dplyr::select(race = fam, id) 
fam_tgp %>% filter(id == "NA19625")
```
```{r}
AFR = c('MSL', 'YRI', "ESN", "GWD", "LWK", "ACB", "ASW")
EUR = c('CEU', 'GBR', 'IBS', 'TSI', 'FIN')
SAS = c('PJL', 'GIH', 'ITU', 'STU', 'BEB')
EAS = c('CHS', 'CDX', 'KHV', 'CHB', 'JPT', 'CHD')
AMR = c('PEL', 'MXL', 'CLM', 'PUR')
pops_annot = as.data.frame(qpcR:::cbind.na(AFR, EUR, SAS, EAS, AMR)) %>% gather(Race, V1) %>% select(Race, race = V1)
```

```{r}
tgp_race = merge(fam_tgp, pops_annot, by = "race", all.x = TRUE) %>% select(-race, famid = id, Race) 


final_merge_pheno = merge(ssnstgp_1, tgp_race, by = "famid", all.x = TRUE) %>% mutate(Group = ifelse(is.na(Race) == TRUE, Group, ifelse(Race == "EUR", "White", ifelse(Race == "SAS", "Asian", ifelse(Race == "EAS", "Asian", ifelse(Race == "AFR", "Black", ifelse(Race == "AMR", "Hispanic", NA))))))) %>% mutate(Phenotype = ifelse(is.na(Phenotype) == TRUE, 0, Phenotype)) %>% select(-ssns_id, -Race)

final_merge_pheno %>% filter(famid == "NA19625")
write.table(final_merge_pheno,"/datacommons/ochoalab/tiffany_data/DATA_NS_MERGE/merge_pheno_race_sex.txt", sep=" ",row.names = FALSE, quote = FALSE)
```



