---
title: "missingness_kin"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
```

```{r}
miss_df <- read.table("duplicate_sample_all_missingness.smiss", sep = "\t", stringsAsFactors=FALSE, quote = "")
colnames(miss_df) <- c("FID", "IID", "MISSING_CT", "OBS_CT", "F_MISS")
f_miss <- miss_df %>% select(IID, F_MISS)
# check. make sure the merge step below is correct
f_miss %>% filter(IID == "19891275d")

kin_df <- read.table("duplicated_related.kin0", sep = "\t", stringsAsFactors=FALSE, quote = "")
colnames(kin_df) <- c("FID1", "ID1", "FID2", "ID2", "NSNP", "HETHET", "IBS0",  "KINSHIP")
# check. make sure the merge step below is correct
kin_df %>% filter(ID1 == "19891275")
```

```{r}
duplicate_df = kin_df %>% select(ID1, ID2)
merge1 = merge(duplicate_df, f_miss, by.x = "ID1", by.y = "IID", all.x = TRUE) %>% rename(F_MISS_1 = F_MISS) 
merge2 = merge(merge1, f_miss, by.x = "ID2", by.y = "IID", all.x = TRUE) %>% rename(F_MISS_2 = F_MISS) 
least_miss = merge2 %>% 
  mutate(least_missing = ifelse(F_MISS_1 > F_MISS_2, 2, 1), 
         to_remove = ifelse(F_MISS_1 > F_MISS_2, ID1, ID2))
```

Use demographic data to further filter
```{r}
phenotype1 = read_xlsx("2022-02-25_2PhenotypeDatafirstDataSets.xlsx", 
               col_names  = TRUE)
phenotype1_2 = read_xlsx("2022-02-25_2PhenotypeDatafirstDataSets.xlsx", 
               col_names  = TRUE, sheet = 2)
phenotype1 = phenotype1 %>% select(AcquisitionNumber = `Acquisition Number`, Sex, RACE, AGE = `AGE DIAGNOSIS`, DIAGNOSIS)
phenotype1_2 = phenotype1_2 %>% select(AcquisitionNumber = `Acquisition Number`, Sex = SEX_CDE, RACE = `Broad Race`, DIAGNOSIS = Diagnosis, AGE = `Age at Diagnosis`)

# check for overlap ID's
intersect(phenotype1$AcquisitionNumber, phenotype1_2$AcquisitionNumber)
# remove repeated rows (info overlap, manually checked)
phenotype1 = phenotype1 %>% 
  filter(AcquisitionNumber != "19891275" & 
           AcquisitionNumber != "19891281" & 
           AcquisitionNumber !=  "A2008755" &
           AcquisitionNumber != "A1024006" & 
           AcquisitionNumber != "A1004719" &
           AcquisitionNumber != "A1004697" &
           AcquisitionNumber != "A1002258")

# combine phenotype data
phenotype1_ = rbind(phenotype1, phenotype1_2)

# load other excel sheet
phenotype2 = read_xlsx("PHENOTYPEDATASECONDSETOFPLATES2021_2022.xlsx", 
               col_names  = TRUE)

# check for overlap ID's
intersect(phenotype1_$AcquisitionNumber, phenotype2$`Acquisition Number`)

# remove repeated rows (information overlap from both phenotype files)
phenotype2 = phenotype2 %>% 
  filter(`Acquisition Number` != "19960560" & `Acquisition Number` != "19960561") %>% 
  select(AcquisitionNumber = `Acquisition Number`, Sex = SEX_CDE, RACE = `Broad Race`, AGE = `Age at Diagnosis`, DIAGNOSIS = Diagnosis)

# combine phenotype data
phenotype_df = rbind(phenotype1_, phenotype2)

# create duplicate
phenotype_df$AcquisitionNumber = paste0(phenotype_df$AcquisitionNumber, "d")
# combine
phenotype_df = rbind(phenotype1_, phenotype2, phenotype_df)
```
```{r}
intentional_dup = unique(c(dplyr::filter(least_miss, grepl("d",ID1)) %>% pull(ID1), dplyr::filter(least_miss, grepl("d",ID2)) %>% pull(ID2)))
```



Add demographic data to missingness/duplicate dataframe
```{r}
merge3 = merge(least_miss, phenotype_df, by.x = "ID1", by.y = "AcquisitionNumber", all.x = TRUE) %>% 
  rename(Sex_1 = Sex, RACE_1 = RACE, AGE_1 = AGE, DIAGNOSIS_1 = DIAGNOSIS) 
merge4 = merge(merge3, phenotype_df, by.x = "ID2", by.y = "AcquisitionNumber", all.x = TRUE) %>% 
  rename(Sex_2 = Sex, RACE_2 = RACE, AGE_2 = AGE, DIAGNOSIS_2 = DIAGNOSIS) %>% select(ID1, ID2, everything())


check_demo = merge4 %>% mutate(check_sex = ifelse(Sex_1 == Sex_2, TRUE, FALSE),
                               check_race = ifelse(RACE_1 == RACE_2, TRUE, FALSE),
                               #check_age = ifelse(AGE_1 == AGE_2, TRUE, FALSE),
                               check_diag = ifelse(DIAGNOSIS_1 == DIAGNOSIS_2, TRUE, FALSE))

# if NA in any of the check columns, then demographic data is incomplete for at least one of the individual
# if FALSE in any of the check columns, then demographic data between duplicates does not match
## get row indices of FALSE entries
id_to_remove = unique(c(which(!check_demo$check_sex), which(!check_demo$check_race), 
                     which(!check_demo$check_diag)))
## subset - ID's to remove:
remove = check_demo[id_to_remove,]
demo_remove = c(remove$ID2, remove$ID1)
```


After removing demographic mismatch, need to select one individual with least missingness from each pair
```{r}
subset_df = check_demo[-id_to_remove,]
list_remove = unique(c(demo_remove, subset_df$to_remove))
# write output txt file
fileConn<-file("duplicate_remove.txt")
writeLines(c(list_remove), fileConn)
close(fileConn)
```




