---
title: "pca analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(data.table)
library(cluster)
library(factoextra)
```

```{r}
# PCA analysis
pca <- read_table2("PCA10.eigenvec")
eigenval <- scan("PCA10.eigenval")
pca <- pca[,-1]

pheno_ <- read.table("/datacommons/ochoalab/ssns_gwas/nephrotic.syndrome.gwas_proprocessing_202205/gwas/pheno_file_new.txt", sep = " ", 
                          stringsAsFactors=FALSE, quote = "")
colnames(pheno_) = c("famid", "id", "pheno")

pheno_complete = read_csv("/datacommons/ochoalab/ssns_gwas/nephrotic.syndrome.gwas_proprocessing_202205/pheno_excelmerge.csv")
pheno_race = pheno_complete %>% filter(AcquisitionNumber %in% pheno_$id) 

pca_race = merge(pca, pheno_race, by.x = "IID", by.y = "AcquisitionNumber")
```

```{r}
ggplot(pca_race, aes(x = PC1, y = PC2, color = RACE)) +
  geom_point() + ggtitle("ssns_maf")
```
## PCA on Asian subset
```{r}
pca_a <- read_table2("PCA10_asian.eigenvec", col_names = TRUE)
pca_a <- pca_a[,-1]
pca_cluster = pca_a %>% dplyr::select(PC1, PC2)
k = 2
kmeans_ = kmeans(pca_cluster, centers = k, nstart = 50)
fviz_cluster(kmeans_, data = pca_cluster, main = "ssns_maf: Asian subset")

cluster_assign = kmeans_$cluster %>% as.data.frame() 
colnames(cluster_assign) = "assign"
cluster_assign %>% mutate(assign = as.factor(assign)) %>% count(assign)
pca_assign = cbind(pca_a, cluster_assign) 

```

```{r}
#outlier_ind = pca_a[c(639, 499),] %>% pull(IID)

outlier_ind = pca_assign %>% filter(assign == 1) %>% pull(IID)

pca_outlier_label = pca_race %>% drop_na(RACE) %>% mutate(RACE = as.factor(ifelse(IID %in% outlier_ind, "outlier_asian", RACE )),
                                        shape = ifelse(RACE == "outlier_asian", 24, 20)) 
pca_outlier_label %>% filter(RACE == "outlier_asian")
ggplot(pca_outlier_label, aes(x = PC1, y = PC2, color = RACE)) +
  ggtitle("ssns_maf") +
  geom_point() + 
  geom_text(aes(label=ifelse(RACE == "outlier_asian",as.character("outlier"),'')),hjust=0,vjust=0, show_guide  = FALSE) 

pca_a[639,]
```

## plot without outlier
```{r}
pca_remove_out = pca_outlier_label %>% filter(RACE != "outlier_asian") %>% filter(RACE == "Asian") %>% dplyr::select(PC1, PC2)
pca_remove = pca_outlier_label %>% filter(RACE != "outlier_asian") %>% filter(RACE == "Asian") 
k = 2
kmeans_ = kmeans(pca_remove_out, centers = k, nstart = 50)
fviz_cluster(kmeans_, data = pca_remove_out, main = "ssns_maf: Asian subset (5 outliers removed)")
cluster_assign = kmeans_$cluster %>% as.data.frame() 

colnames(cluster_assign) = "assign"
cluster_assign %>% mutate(assign = as.factor(assign)) %>% count(assign)
pca_assign_new = cbind(pca_remove, cluster_assign) 
pca_assign_new[633,]

outlier_ind_new = pca_assign_new %>% filter(assign == 1) %>% pull(IID)
outlier_all = c(outlier_ind_new, outlier_ind)
pca_outlier_label_new = pca_race %>% drop_na(RACE) %>% mutate(RACE = as.factor(ifelse(IID %in% outlier_ind_new, "cluster2", RACE )),
                                        shape = ifelse(RACE == "cluster2", 24, 20)) 

pca_outlier_label_new %>% filter(RACE == "cluster2")
ggplot(pca_outlier_label_new, aes(x = PC1, y = PC2, color = RACE)) +
  ggtitle("ssns_maf") +
  geom_point() + 
  geom_text(aes(label=ifelse(RACE == "cluster2",as.character("clutser2"),'')),hjust=0,vjust=0, show_guide  = FALSE)  +
  scale_color_manual(values = c("gray", "gray", "red",
                                "gray", "gray", "gray","gray","gray","gray"))
```


## plink1.9 neighbor calculation

```{r}
asian_neighbor <- read.table("/datacommons/ochoalab/ssns_gwas/nephrotic.syndrome.gwas_proprocessing_202205/pca/PCA_neighbor_asian.nearest", header = TRUE)

asian_outlier_id = asian_neighbor %>% filter(Z< -3) %>% pull(IID)
length(unique(asian_outlier_id))
pca_outlier_label = pca_race %>% drop_na(RACE) %>% mutate(RACE = as.factor(ifelse(IID %in% asian_outlier_id, "outlier_asian", RACE )),
                                        shape = ifelse(RACE == "outlier_asian", 24, 20)) %>% arrange(shape)
pca_outlier_label %>% filter(RACE == "outlier_asian")
ggplot(pca_outlier_label, aes(x = PC1, y = PC2, color = RACE)) +
  ggtitle("ssns_maf (Z < -3)") +
  geom_point() + 
  #geom_text(aes(label=ifelse(RACE == "outlier_asian",as.character("outlier"),'')),hjust=0,vjust=0, show_guide  = FALSE) +
  scale_color_manual(values = c("gray", "gray",
                                "gray", "gray", "gray", "red", "gray","gray","gray"))
```

## k-medioids method
```{r}
library(cluster)
pca_a_scale <- scale(pca_remove_out[-633,]) 
fviz_nbclust(pca_a_scale, pam, method = "wss")
kmed = pam(pca_a_scale, k = 3, metric = "euclidean", stand = FALSE)
fviz_cluster(kmed, data = pca_a_scale)
cluster_assign = kmed$clustering %>% as.data.frame() 

colnames(cluster_assign) = "assign"
cluster_assign %>% mutate(assign = as.factor(assign)) %>% count(assign)
pca_assign_new = cbind(pca_remove[-633,], cluster_assign) 
id_cluster1 = pca_assign_new %>% filter(assign == 1) %>% pull(IID)
id_cluster2 = pca_assign_new %>% filter(assign == 2) %>% pull(IID)
id_cluster3 = pca_assign_new %>% filter(assign == 3) %>% pull(IID)
pca_outlier_label_new = pca_race %>% drop_na(RACE) %>% mutate(RACE = as.factor(ifelse(IID %in% id_cluster1, "cluster1", ifelse(IID %in% id_cluster2, "cluster2", ifelse(IID %in% id_cluster3, "cluster3", RACE) )))) %>% filter(RACE != "Asian") #%>% filter(RACE != "cluster2")

pca_outlier_label_new %>% filter(RACE == "Asian")
ggplot(pca_outlier_label_new, aes(x = PC2, y = PC3, color = RACE)) +
  ggtitle("ssns_maf") +
  geom_point(alpha = 0.8) + 
  #geom_text(aes(label=ifelse(RACE == "cluster2",as.character("clutser2"),'')),hjust=0,vjust=0, show_guide  = FALSE)  +
  scale_color_manual(values = c("gray", "red", "green",
                                "blue", "gray", "gray","gray","gray","gray"))
```
```{r}
pca_outlier_label_new = pca_race %>% drop_na(RACE) %>% mutate(RACE = as.factor(ifelse(IID %in% id_cluster1, "cluster1", ifelse(IID %in% id_cluster2, "cluster2", ifelse(IID %in% id_cluster3, "cluster3", RACE) )))) %>% filter(RACE != "Asian")

pca_outlier_label_new %>% filter(RACE == "Asian")
ggplot(pca_outlier_label_new, aes(x = PC1, y = PC2, color = RACE)) +
  ggtitle("ssns_maf") +
  geom_point(alpha = 0.8) + 
  #geom_text(aes(label=ifelse(RACE == "cluster2",as.character("clutser2"),'')),hjust=0,vjust=0, show_guide  = FALSE)  +
  scale_color_manual(values = c("#E69F00", "gray", "gray",
                                "gray", "#56B4E9", "#009E73","#F0E442","gray","#CC79A7"))
```

