---
title: "rc"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
```

# check allele inputs
```{r}
df2 = read_xlsx("/Users/tiffanytu/Documents/Duke.grad/2022spring/lab/rachel/0504VariantLoads.xlsx", col_names  = TRUE)
```
```{r}
df2_names
```


```{r}
df2_names = colnames(df2)
# input: T/C
input = c("T", "C")
df2$`HLA-DQA1 rs1071630 T/C ( C)`

grepl( paste(patterns, collapse="|"), "T/C", fixed = TRUE)

patterns <- c("C", "T")
paste(patterns, collapse="|")
```
```{r}
df2[is.na(df2)] <-'0'
```

```{r}
pattern <- "G|A|0"
which(!grepl(pattern, df2$`HLA-DQA1 rs1129740 G/A (A)`))
df2[839,]
```

```{r}
pattern <- "C|T|0"
which(!grepl(pattern, df2$`HLA-DQA1 rs1071630 T/C ( C)`))
df2[4,]
```
```{r}
pattern <- "A|T|0"
which(!grepl(pattern, df2$`BTNL2 rs9348883 T/A (A)`))
#none
pattern <- "G|T|0"
which(!grepl(pattern, df2$`HLA-DR/DQ rs4642516 G/T (G)`))
#none
pattern <- "A|T|0"
which(!grepl(pattern, df2$`HLA-DR/DQ rs3134996 A/T (A)`))
#none
pattern <- "C|T|0"
which(!grepl(pattern, df2$`Intergenic rs9273371 C/T (T)`))
df2[4,]
pattern <- "C|T|0"
which(!grepl(pattern, df2$`CALHM6 rs2637678 T/C ( C)`))
df2[4,]
pattern <- "G|A|0"
which(!grepl(pattern, df2$`NPHS1/KIRREL rs56117924 G/A (A)`))
#none
pattern <- "G|A|0"
which(!grepl(pattern, df2$`TNFSF15 rs6478109 A/G (A)`))
#none
pattern <- "C|A|0"
which(!grepl(pattern, df2$`TNFRSF11A rs34213471 C/A (A)`))
#none
```
```{r}
pattern <- "G|T|0"
which(!grepl(pattern, df2$`HLA-DR/DQ rs4642516 G/T (G)`))
#none

```

## 05/09 updated data:

```{r}
df3 = read_xlsx("/Users/tiffanytu/Documents/Duke.grad/2022spring/lab/rachel/May10_VariantLoad.xlsx", col_names  = TRUE, sheet = 2) 
df3_clean = df3[-c(1:3), -c(17:18)]
```

```{r}
df3_ssnssrns = df3_clean %>% rename(`HLA-DQA1 rs1129740 G/A (G)` = `HLA-DQA1 rs1129740 G/A`,
                                    `HLA-DQA1 rs1071630 T/C ( T)` = `HLA-DQA1 rs1071630 T/C`,
                                    `BTNL2 rs9348883 T/A (A)` = `BTNL2 rs9348883 T/A`,
                                    `HLA-DR/DQ rs4642516 G/T (G)` = `HLA-DR/DQ rs4642516 G/T`,
                                    `HLA-DR/DQ rs3134996 A/T (T)` = `HLA-DR/DQ rs3134996 A/T`,
                                    `Intergenic rs9273371 C/T (C)` = `Intergenic rs9273371 C/T`,
                                    `CALHM6 rs2637678 T/C ( C)` = `CALHM6 rs2637678 T/C`,
                                    `NPHS1/KIRREL rs56117924 G/A (G)_na` = `NPHS1/KIRREL rs56117924 G/A`,
                                    `TNFSF15 rs6478109 A/G (A)_na` = `TNFSF15 rs6478109 A/G`,
                                    `TNFRSF11A rs34213471 C/A (C)` = `TNFRSF11A rs34213471 C/A`)

df3_ifrfrsd = df3_clean %>% rename(`HLA-DQA1 rs1129740 G/A (A)` = `HLA-DQA1 rs1129740 G/A`,
                                    `HLA-DQA1 rs1071630 T/C ( C)` = `HLA-DQA1 rs1071630 T/C`,
                                    `BTNL2 rs9348883 T/A (T)_na` = `BTNL2 rs9348883 T/A`,
                                    `HLA-DR/DQ rs4642516 G/T (T)` = `HLA-DR/DQ rs4642516 G/T`,
                                    `HLA-DR/DQ rs3134996 A/T (A)` = `HLA-DR/DQ rs3134996 A/T`,
                                    `Intergenic rs9273371 C/T (T)_na` = `Intergenic rs9273371 C/T`,
                                    `CALHM6 rs2637678 T/C ( C)_na` = `CALHM6 rs2637678 T/C`,
                                    `NPHS1/KIRREL rs56117924 G/A (G)` = `NPHS1/KIRREL rs56117924 G/A`,
                                    `TNFSF15 rs6478109 A/G (G)_na` = `TNFSF15 rs6478109 A/G`,
                                    `TNFRSF11A rs34213471 C/A (A)_na` = `TNFRSF11A rs34213471 C/A`)
```


Functions:
```{r}
# function for counting occurence
occurence_count <- function(x, allele){
  occur = str_count(x, allele)
  return(occur)
}

# function for total allele count
total_count <- function(x){
  count = nchar(gsub("/|\\d", "", x))
  return(count)
}

risk_allele_count <- function(x, df){
  occur_df = c()
  allele_df = c()
  # iterate through columns
  for (col in x){
    col_n = colnames(df)
    each_col = col_n[col]
    # extract risk allele from column name
    risk_allele = stringr::str_extract(string = each_col, pattern = "(?<=\\().*(?=\\))")
    # remove any extra spaces
    risk_allele_clean = gsub(" ", "", risk_allele, fixed = TRUE)
  
    # create vector that saves occurence of risk allele for each individual
    risk_count =  lapply(df[col], occurence_count, allele = risk_allele_clean) %>% unlist()
    occur_df = cbind(occur_df, risk_count) %>% as.data.frame()
    
    # create vector that saves count of total alleles
    allele_count = lapply(df[col], total_count) %>% unlist()
    allele_df = cbind(allele_df, allele_count) %>% as.data.frame()
  }
  
  # clean up occurence of risk allele df
  orig_names = colnames(df %>% select(x))
  colnames(occur_df) = paste0(orig_names, "_riskcount")
  rownames(occur_df) <- NULL
  # row sum of risk allele counts
  risk_sum = apply(occur_df, 1, sum) %>% as.vector()
  print(occur_df)
  # clean up total allele count df
  colnames(allele_df) = paste0(orig_names, "_totalcount")
  rownames(allele_df) <- NULL
  # row sum of risk allele counts
  total_sum = apply(allele_df, 1, sum) %>% as.vector()
  output = cbind(df, risk_sum, total_sum) 
  return(output)
}

```

```{r}
df3_ssnssrns[is.na(df3_ssnssrns)] <-'0'
# define columns of interest
x <- c(7, 8, 9, 10, 11, 12, 13, 16)
#colnames(df3_ssnssrns)
risk_ssnssrns = risk_allele_count(x, df3_ssnssrns)

df3_ifrfrsd[is.na(df3_ifrfrsd)] <-'0'
# define columns of interest
x <- c(7, 8, 10, 11, 14)
#colnames(df3_ifrfrsd)
risk_ifrfrsd = risk_allele_count(x, df3_ifrfrsd)
```
```{r}
library(ggplot2)
library(gridExtra)
p1 = risk_ssnssrns %>%
  ggplot( aes(x=total_sum, fill=as.factor(Phenotype))) +
  geom_histogram( color="#e9ecef", position = "dodge") +
  ggtitle("SSNS vs SRNS")
```

```{r}
p2 = risk_ifrfrsd %>%
  ggplot( aes(x=total_sum, fill=as.factor(Phenotype))) +
  geom_histogram( color="#e9ecef", position = 'dodge', bins = 30) +
  ggtitle("IFR vs FRSD")

```

