---
title: "Write txt files for sub analyese"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(genio)
```

```{r}
covar = read.table("/datacommons/ochoalab/ssns_gwas/nephrotic.syndrome.gwas_proprocessing_202205/allele_freq/newfiles_alpha/imputation_10_new/results/gcta/covar_ns_tgp_new.txt", sep = " ", stringsAsFactors=FALSE, quote = "", header = TRUE)
phenotype_df = read_csv("/datacommons/ochoalab/ssns_gwas/nephrotic.syndrome.gwas_proprocessing_202205/pheno_excelmerge.csv")

name <- '/datacommons/ochoalab/ssns_gwas/nephrotic.syndrome.gwas_proprocessing_202205/allele_freq/newfiles_alpha/imputation_10_new/results/ssns_tgp_imp_mac_10'
fam_ssns <- read_fam( name ) %>% arrange(fam_ssns)
tail(fam_ssns)

length(intersect(phenotype_df$AcquisitionNumber, fam_ssns$id))
pheno_mac_NS = filter(phenotype_df, AcquisitionNumber %in% fam_ssns$id) %>% distinct() %>% arrange(AcquisitionNumber)
pheno_mac_NS_control = pheno_mac_NS %>% filter(DIAGNOSIS == "Control") %>% select(id = AcquisitionNumber)
pheno_mac_tgp = fam_ssns %>% filter(!(id %in% phenotype_df$AcquisitionNumber)) %>% select(id)

pheno_control = rbind(pheno_mac_NS_control, pheno_mac_tgp) %>% mutate(V1 = 0, pheno = 1)
  
pheno_ssns = pheno_mac_NS %>% filter(DIAGNOSIS == "SSNS")
pheno_srns = pheno_mac_NS %>% filter(DIAGNOSIS == "SRNS")

########################
# id for ssns vs control:
ssns_ctr = cbind(0, c(pheno_ssns$AcquisitionNumber, pheno_control$id)) %>% as.data.frame()
write.table(ssns_ctr, "/datacommons/ochoalab/ssns_gwas/nephrotic.syndrome.gwas_proprocessing_202205/allele_freq/newfiles_alpha/imputation_10_new/results/case_control/ssns_ctr.txt", row.names=FALSE, quote=FALSE, col.names=FALSE)

# pheno
name <- '/datacommons/ochoalab/ssns_gwas/nephrotic.syndrome.gwas_proprocessing_202205/allele_freq/newfiles_alpha/imputation_10_new/results/case_control/ssns_ctr'
fam_ssns_ctr <- read_fam( name ) %>% select(fam, id)
ssns_ctr_pheno = cbind(0, rbind(cbind(pheno_ssns$AcquisitionNumber, 2), cbind(pheno_control$id,1))) %>% as.data.frame() %>% rename(fam = V1, id = V2, pheno = V3)
table(ssns_ctr_pheno$pheno)
ssns_ctr_pheno_order = merge(fam_ssns_ctr, ssns_ctr_pheno, by = c("fam", "id"))
table(ssns_ctr_pheno_order$pheno)
write.table(ssns_ctr_pheno_order, "/datacommons/ochoalab/ssns_gwas/nephrotic.syndrome.gwas_proprocessing_202205/allele_freq/newfiles_alpha/imputation_10_new/results/case_control/ssns_ctr_pheno.txt", row.names=FALSE, quote=FALSE, col.names=FALSE)

# covar
ssns_ctr_covar = covar %>% filter(IID %in% ssns_ctr_pheno_order$id)
write.table(ssns_ctr_covar, "/datacommons/ochoalab/ssns_gwas/nephrotic.syndrome.gwas_proprocessing_202205/allele_freq/newfiles_alpha/imputation_10_new/results/case_control/ssns_ctr_covar.txt", row.names=FALSE, quote=FALSE, col.names=FALSE)

########################
# id for srns vs control:
srns_ctr = cbind(0, c(pheno_srns$AcquisitionNumber, pheno_control$id)) %>% as.data.frame()
write.table(srns_ctr, "/datacommons/ochoalab/ssns_gwas/nephrotic.syndrome.gwas_proprocessing_202205/allele_freq/newfiles_alpha/imputation_10_new/results/case_control/srns_ctr.txt", row.names=FALSE, quote=FALSE, col.names=FALSE)

# pheno
name <- '/datacommons/ochoalab/ssns_gwas/nephrotic.syndrome.gwas_proprocessing_202205/allele_freq/newfiles_alpha/imputation_10_new/results/case_control/srns_ctr'
fam_srns_ctr <- read_fam( name ) %>% select(fam, id)
srns_ctr_pheno = cbind(0, rbind(cbind(pheno_srns$AcquisitionNumber, 2), cbind(pheno_control$id,1))) %>% as.data.frame() %>% rename(fam = V1, id = V2, pheno = V3)
table(srns_ctr_pheno$pheno)
srns_ctr_pheno_order = merge(fam_srns_ctr, srns_ctr_pheno, by = c("fam", "id"))
table(srns_ctr_pheno_order$pheno)
write.table(srns_ctr_pheno_order, "/datacommons/ochoalab/ssns_gwas/nephrotic.syndrome.gwas_proprocessing_202205/allele_freq/newfiles_alpha/imputation_10_new/results/case_control/srns_ctr_pheno.txt", row.names=FALSE, quote=FALSE, col.names=FALSE)

# covar
srns_ctr_covar = covar %>% filter(IID %in% srns_ctr_pheno_order$id)
write.table(srns_ctr_covar, "/datacommons/ochoalab/ssns_gwas/nephrotic.syndrome.gwas_proprocessing_202205/allele_freq/newfiles_alpha/imputation_10_new/results/case_control/srns_ctr_covar.txt", row.names=FALSE, quote=FALSE, col.names=FALSE)

########################
# id for ssns vs srns
ssns_srns = cbind(0, c(pheno_ssns$AcquisitionNumber, pheno_srns$AcquisitionNumber)) %>% as.data.frame()
write.table(ssns_srns, "/datacommons/ochoalab/ssns_gwas/nephrotic.syndrome.gwas_proprocessing_202205/allele_freq/newfiles_alpha/imputation_10_new/results/case_control/ssns_srns.txt", row.names=FALSE, quote=FALSE, col.names=FALSE)

# pheno
name <- '/datacommons/ochoalab/ssns_gwas/nephrotic.syndrome.gwas_proprocessing_202205/allele_freq/newfiles_alpha/imputation_10_new/results/case_control/ssns_srns'
fam_ssns_srns <- read_fam( name ) %>% select(fam, id)
ssns_srns_pheno = cbind(0, rbind(cbind(pheno_ssns$AcquisitionNumber, 1), cbind(pheno_srns$AcquisitionNumber,2))) %>% as.data.frame() %>% rename(fam = V1, id = V2, pheno = V3)
table(ssns_srns_pheno$pheno)
ssns_srns_pheno_order = merge(fam_ssns_srns, ssns_srns_pheno, by = c("fam", "id"))
table(ssns_srns_pheno_order$pheno)
write.table(ssns_srns_pheno_order, "/datacommons/ochoalab/ssns_gwas/nephrotic.syndrome.gwas_proprocessing_202205/allele_freq/newfiles_alpha/imputation_10_new/results/case_control/ssns_srns_pheno.txt", row.names=FALSE, quote=FALSE, col.names=FALSE)

# covar
ssns_srns_covar = covar %>% filter(IID %in% ssns_srns_pheno_order$id)
write.table(ssns_srns_covar, "/datacommons/ochoalab/ssns_gwas/nephrotic.syndrome.gwas_proprocessing_202205/allele_freq/newfiles_alpha/imputation_10_new/results/case_control/ssns_srns_covar.txt", row.names=FALSE, quote=FALSE, col.names=FALSE)

```



